---
title: "Lung trioxidation"
author: "Jose Antonio"
date: "2022-10-07"
output:
  html_document: default
  pdf_document: default
---

```{r, imports, include = F}
library(ggplot2)
library(ggpubr)
library(dplyr)
library(biomaRt)
library(VennDiagram)
library(limma)
library(edgeR)
library(tidyverse)
library(org.Mm.eg.db)
library(clusterProfiler)
library(kableExtra)
datos = read.delim("Young_Old_mice_O3.xlsx - O3_All_Pep_E05_T20131023_EXQ8_H.csv", header = T, sep = ",")
old = grep("_old_", datos$MS.MS)
young = grep("_young_", datos$MS.MS)
datos$age = "Y"
datos$age[young] = "young"
datos$age[old] = "old"
rep1 = grep("_1_", datos$MS.MS)
rep2 = grep("_2_", datos$MS.MS) 
rep3 = grep("_3_",datos$MS.MS)
rep4 = grep("_4_",datos$MS.MS)
grupECM = grep("_ECM_", datos$MS.MS)
grupFR = grep("_FR", datos$MS.MS)
datos$rep = "rep"
datos$sample = "sample"
datos$rep[rep1] = "g01"
datos$rep[rep2] = "g02"
datos$rep[rep3] = "g03"
datos$rep[rep4] = "g04"
datos$sample[grupECM] = "ECM"
datos$sample[grupFR] = "FR"


datos$GS = gsub("GN=","",datos$GS)

```

# Trioxidation in mouse Lungs


```{r, box1, echo = F, include = F}
### Total Triox Peptides
### Total Triox Peptides
c = table(datos[c("GS", "age")])
c1 = table(datos[c("Pep", "age")])
box = as.data.frame(c)
box1 = as.data.frame(c1)
#ggboxplot(box, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "Age", ylab = "Number of peptides", main = "Total Peptides per Protein") + stat_compare_means() + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5)
ggboxplot(box1, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "Age", ylab = "Number of peptides", main = "Total Peptides per age group") + stat_compare_means() + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5)

totales_p = addmargins(c1)
write.csv(totales_p, file= "peptides_lung.csv")
totales = addmargins(c)
write.csv(totales, file = "Total_peptides_lung.csv")
table(datos$age)
df = as.data.frame(table(datos$GS))
df_ord = df[order(df$Freq),]
tail(df_ord)
```


```{r, box2, echo = F, warning= F}
### Peptides with same modifications


uniq = unique(datos[c("GS" ,"age","Pep","prot_matches_sig","rep")])
uniq1 = unique(datos[c("age","Pep","prot_matches_sig","rep")])
b = table(uniq[,c("GS", "age")])
b1 = table(uniq1[,c("Pep","age")])
box1 = as.data.frame(b)
box2 = as.data.frame(b1)
#ggboxplot(box1, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Peptides", main = "Number of peptides per protein") + stat_compare_means() + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5)

ggboxplot(box2, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Peptides", main = "Number of different peptides grouped by age") + stat_compare_means() + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5)

totales_unicos = addmargins(b)
write.csv(totales_unicos, file = "Unique_peptides_skin.csv")


table(uniq$age)


uniq1 = unique(uniq[c("GS", "age")])

young = uniq1$GS[which(uniq1$age == "young")]
old = uniq1$GS[which(uniq1$age == "old")]



#venn.diagram( x = list(young, old), category.names = c("young", "old"), filename = "venn_lung.png", output = T)

```

### Number of trioxidations per protein



```{r, box3, echo = F, warning= F}
triox = str_count(datos$Pep1, "C3")
datos$triox =triox
posiciones = datos$pep_var_mod_pos %>% str_locate_all("3") %>% sapply(., function(x) x[,1]) 


lista = list()
for(x in 1:length(posiciones)){
  inicial = datos$pep_start[x]
  sum = unlist(posiciones[x]) + inicial-3
  lista = append(lista, list(sum))
  }


df = as.data.frame(do.call(rbind, lista))
datos = cbind(datos, df)
datos$pos = paste(datos$V1, datos$V2, datos$V3, sep = " ")

datos$pos = Map(unique, strsplit(datos$pos, " "))
datos$pos = as.character(datos$pos)
datos$pos = gsub("c", "", gsub('"', "",datos$pos))
datos$pos = gsub("[()]", "", datos$pos)



write.csv(datos, file = "procesed_data_lungs.csv")

uniq = unique(datos[c("GS" ,"age","pos","triox", "rep")])
ag = aggregate(uniq$triox, by = list(uniq$age, uniq$GS, uniq$rep), FUN = sum)

uni = unique(datos[c("GS" ,"age","pos","triox")])
uni1 = unique(datos[c("Pep" ,"age","pos","triox")])

b = table(uni[,c("GS", "age")])
b1 = table(uni1[,c("Pep", "age")])
box1 = as.data.frame(b)
box2 = as.data.frame(b1)
ggboxplot(box1, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Trioxidations", main= "Number of Trioxidations per protein") + stat_compare_means() + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5) + labs(caption = "Boxplot of the number of trioxidations grouped by protein and age")
totales_unicos = addmargins(b)

write.csv(totales_unicos, file = "triox_proteins_lung.csv")

ggboxplot(box2, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Trioxidations", main= "Number of Trioxidations per Peptide") + stat_compare_means() + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5) + labs(caption = "Boxplot of the number of trioxidations grouped by peptide and age")

g01_old = ag[ag$Group.1 =="old" & ag$Group.3 == "g01",]
g02_old = ag[ag$Group.1 =="old" & ag$Group.3 == "g02",]
g03_old = ag[ag$Group.1 =="old" & ag$Group.3 == "g03",]
g04_old = ag[ag$Group.1 =="old" & ag$Group.3 == "g04",]
g01_young = ag[ag$Group.1 =="young" & ag$Group.3 == "g01",]
g02_young = ag[ag$Group.1 =="young" & ag$Group.3 == "g02",]
g03_young = ag[ag$Group.1 =="young" & ag$Group.3 == "g03",]
g04_young = ag[ag$Group.1 =="young" & ag$Group.3 == "g04",]

lista = list(g01_old, g02_old, g03_old, g04_old, g01_young,g02_young, g03_young,g04_young)
junto = purrr::reduce(lista,full_join, by='Group.2')
df_final = junto[,c(4,7,10,13,16,19,22,25)]
colnames(df_final) = c("g01_old", "g02_old", "g03_old", "g04_old", "g01_young","g02_young", "g03_young","g04_young")
rownames(df_final) = junto$Group.2

df_final[is.na(df_final)] = 0

df_final = mutate(df_final, old = (g01_old + g02_old + g03_old + g04_old)/4, young = (g01_young + g02_young + g03_young + g04_young)/4)

write.csv(df_final, file = "triox_count_lung.csv")

datos_tabla_larga = gather(data = df_final[,c("old","young")], key = "group", value = "triox")

#ggplot(data = datos_tabla_larga, aes(x = group, y = triox, colour = group)) +
 #   geom_boxplot() +
  #  theme_bw() +
   # theme(legend.position = "none") + stat_compare_means()


```

### Differential expression analysis


```{r, box4, echo = F, warning= F}

uniq = unique(datos[c("GS" ,"age","Pep","prot_matches_sig", "sample", "rep")])
agrup2 = aggregate(uniq$prot_matches_sig, by = list(uniq$age, uniq$GS, uniq$sample, uniq$rep), FUN = sum)


#Grupos
g01_old_FR = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g01" & agrup2$Group.3 == "FR",]
g02_old_FR = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g02" & agrup2$Group.3 == "FR",]
g03_old_FR = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g03" & agrup2$Group.3 == "FR",]
g04_old_FR = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g04" & agrup2$Group.3 == "FR",]
g01_young_FR = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g01" & agrup2$Group.3 == "FR",]
g02_young_FR = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g02" & agrup2$Group.3 == "FR",]
g03_young_FR = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g03" & agrup2$Group.3 == "FR",]
g04_young_FR = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g04" & agrup2$Group.3 == "FR",]
g01_old_ECM = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g01" & agrup2$Group.3 == "ECM",]
g02_old_ECM = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g02" & agrup2$Group.3 == "ECM",]
g03_old_ECM = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g03" & agrup2$Group.3 == "ECM",]
g04_old_ECM = agrup2[agrup2$Group.1 =="old" & agrup2$Group.4 == "g04" & agrup2$Group.3 == "ECM",]
g01_young_ECM = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g01" & agrup2$Group.3 == "ECM",]
g02_young_ECM = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g02" & agrup2$Group.3 == "ECM",]
g03_young_ECM = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g03" & agrup2$Group.3 == "ECM",]
g04_young_ECM = agrup2[agrup2$Group.1 =="young" & agrup2$Group.4 == "g04" & agrup2$Group.3 == "ECM",]


lista = list(g01_old_ECM, g02_old_ECM, g03_old_ECM,g04_old_ECM,g01_young_ECM,g02_young_ECM,g03_young_ECM,g04_young_ECM, g01_old_FR, g02_old_FR,g03_old_FR,g04_old_FR,g01_young_FR,g02_young_FR,g03_young_FR,g04_young_FR)
junto = purrr::reduce(lista,full_join, by='Group.2')
df_final = junto[,c(5,9,13,17,21,25,29,33,37,41,45,49,53,57,61,65)]
colnames(df_final) = c("g01_old_ECM","g02_old_ECM","g03_old_ECM","g04_old_ECM","g01_young_ECM","g02_young_ECM","g03_young_ECM","g04_young_ECM","g01_old_FR","g02_old_FR","g03_old_FR","g04_old_FR","g01_young_FR","g02_young_FR","g03_young_FR","g04_young_FR")

rownames(df_final) = junto$Group.2
df_final[is.na(df_final)] = 0
metadatos = unique(datos[,c("GS","prot_desc")])
df_final$GS = rownames(df_final)
metadatos1 = merge(df_final, metadatos, by = "GS", all.x = T)

write.csv(df_final, file = "prot_match_lung.csv")

df_final = df_final[,1:16]

totals = apply(X= df_final, MARGIN=2, FUN= sum)
mean = c(mean(totals[1:4]), mean(totals[5:8]), mean(totals[9:12]), mean(totals[13:16]))
sd = c(sd(totals[1:4]), sd(totals[5:8]), sd(totals[9:12]), sd(totals[13:16]))


tot = cbind(mean, sd)
rownames(tot) = c("old_ECM","young_ECM","old_FR","young_FR")
tot

df_final = mutate(df_final, old = (g01_old_ECM + g02_old_ECM + g03_old_ECM + g04_old_ECM + g01_old_FR + g02_old_FR + g03_old_FR + g04_old_FR)/8, young = (g01_young_ECM + g02_young_ECM + g03_young_ECM + g04_young_ECM + g01_young_FR + g02_young_FR + g03_young_FR + g04_young_FR)/8)

datos_tabla_larga = gather(data = df_final[,c("old","young")], key = "group", value = "prot_matches_sig")

df_final = df_final[,1:16]

#ggplot(data = datos_tabla_larga, aes(x = group, y = prot_matches_sig, colour = prot_matches_sig)) +
 #   geom_boxplot() +
  #  theme_bw() +
   # theme(legend.position = "none") + stat_compare_means()



groups = gsub("g0._","", colnames( df_final ))
groups = factor(groups, levels = c("old_ECM","young_ECM","old_FR","young_FR"))


design = model.matrix( ~ 0 + groups )
colnames(design) = c("old_ECM","young_ECM","old_FR","young_FR")
dge = DGEList(counts=df_final);
dge = calcNormFactors(dge, method = "TMM")  
v = voom(dge, design)
fit = lmFit(v, design) 

cont.matrix = makeContrasts(oldFRvsyoungEFR = old_FR- young_FR, oldECMvsyoungECM = old_ECM - young_ECM, levels=design)
fit2 = contrasts.fit(fit, cont.matrix)
fit2 =  eBayes(fit2, trend=FALSE)
toptable = topTable(fit2, number = "all", confint=TRUE, adjust.method = "BH")

table(toptable$P.Value < 0.05)


df_final = as.matrix(df_final)
heatmap(df_final, margins = c(10,10))

sigp = toptable[which(toptable$P.Value < 0.05),]
sigp$GS = rownames(sigp)
tabla_sigp = merge(sigp, metadatos, by = "GS")

up_FR = sigp[which(sigp$oldFRvsyoungEFR > 0),]


matriz_sig = df_final[up_FR$GS,8:16]
write.csv(matriz_sig, file ="matriz_sig.csv")

mat = as.matrix(matriz_sig)
heatmap(mat)

up_FR %>%
  kbl(caption = "Proteins with different Trioxidation in old vs young mouse") %>%
  kable_classic(full_width = F, html_font = "Cambria")  %>% footnote(general = "Proteins more present in the older groups in relation to the younger groups. All p-values are < 0.05",footnote_as_chunk = T)

write.csv(tabla_sigp, file = "sig_results_lung.csv")


```

### Over representation Analysis

```{r, box5, echo = F, warning= F}


ego  = enrichGO(gene          = up_FR$GS,
                keyType =     "SYMBOL",
                OrgDb         = org.Mm.eg.db,
                ont           = "ALL",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                readable      = TRUE)

ego_BP = ego[ego$ONTOLOGY == "BP" & ego$Count > 4,]


ego_BP %>%
  kbl(caption = "Biological Process") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% footnote(general = "Biological Processes of proteins more present in the older groups in relation to the younger groups. All p-values are < 0.05",footnote_as_chunk = T)

write.csv(ego, file = "ora_lung.csv")

org = org.Mm.eg.db


ids = bitr(up_FR$GS, fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org)
dedup_ids = ids[!duplicated(ids[c("SYMBOL")]),]
df2 = up_FR[up_FR$GS %in% dedup_ids$SYMBOL,]
df2 = merge(x = df2, y = dedup_ids, by.x = "GS", by.y = "SYMBOL")

kegg = enrichKEGG(gene = df2$ENTREZID, organism = 'mmu', pvalueCutoff = 0.05)

kegg %>%
  kbl(caption = "Kegg Pathways") %>%
  kable_classic(full_width = F, html_font = "Cambria")  %>% footnote(general = "KEGG pathways of proteins more present in the older groups in relation to the younger groups. All p-values are < 0.05",footnote_as_chunk = T)


write.csv(kegg, file = "rutas_ora_lung.csv")
```


### Gene Set Enrichment Analysis

```{r, box6, echo = F, warning= F}

genelist = toptable[,"oldFRvsyoungEFR"]
names(genelist) = rownames(toptable)
genelist = sort(genelist, decreasing = T)

gse = gseGO(geneList = genelist, 
             ont ="ALL", 
             keyType = "SYMBOL", 
             nPerm = 10000, 
             minGSSize = 3, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org,
             pAdjustMethod = "none")

write.csv(gse, file = "gse_lung.csv")

dotplot(gse, showCategory=5, split=".sign", x = "count", decreasing = T) + facet_grid(.~.sign) %>% labs(caption = "Gene Ontology terms enriched (NES value > 0) or depleted (NES value < 0) in older mices in relation to young mices")


gse_pos = gse[gse$ONTOLOGY == "BP" & gse$enrichmentScore > 0 & gse$setSize > 9,]

gse_pos %>%
  kbl(caption = "Gene Set Enrichment Analysis") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% footnote(general = "Gene Ontology terms enriched (NES value > 0) or depleted (NES value < 0) in older mices in relation to young mices",footnote_as_chunk = T)

ids = bitr(names(genelist), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org)
dedup_ids = ids[!duplicated(ids[c("SYMBOL")]),]
df2 = toptable[rownames(toptable) %in% dedup_ids$SYMBOL,]
df2$X = rownames(df2)
df2 = merge(x = df2, y = dedup_ids, by.x = "X", by.y = "SYMBOL")
kegg_gene_list =  df2$oldFRvsyoungEFR
names(kegg_gene_list) = df2$ENTREZID
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)

kk2 = gseKEGG(geneList     =  kegg_gene_list,
               organism     = "mmu",
               nPerm        = 10000,
               minGSSize    = 2,
               maxGSSize    = 800,
               pvalueCutoff = 0.05,
               pAdjustMethod = "none",
               keyType       = "ncbi-geneid")

write.csv(kk2, file = "rutas_gse_lung.csv")


#kk2 %>%
  #kbl(caption = "Kegg Pathways") %>%
  #kable_classic(full_width = F, html_font = "Cambria")

#dotplot(kk2, showCategory = 5, title = "Enriched Pathways" , split=".sign") + facet_grid(.~.sign)


```