---
title: "Skin trioxidation"
author: "Jose Antonio"
date: "2022-10-07"
output:
  html_document: default
  pdf_document: default
---


```{r imports, echo = F, include = FALSE}
setwd(".")
require(venn)
datos = read.delim("datos raton - O3_All_PTM_E05_T181119_SKIN_M_2.csv", header = T, sep= ",")
library(ggplot2)
library(ggpubr)
library(dplyr)
library(biomaRt)
library(VennDiagram)
library(tidyverse)
library(edgeR)
library(clusterProfiler)
library(org.Mm.eg.db)
library(limma)
library(stringr)
library(kableExtra)
require(DOSE)

f = grep("_SKIN_F", datos$MS.MS)
m = grep("_SKIN_M", datos$MS.MS)
y01 = grep("_01_", datos$MS.MS)
y06 = grep("_06_", datos$MS.MS)
y18 = grep("_18_", datos$MS.MS)
y24 = grep("_24_", datos$MS.MS)
datos$sex = "S"
datos$sex[f] ="F"
datos$sex[m] = "M"
datos$age = "E"
datos$age[y01] = "01"
datos$age[y06] = "06"
datos$age[y18] = "18"
datos$age[y24] = "24"
repA = grep("A_", datos$MS.MS)
repB = grep("B_", datos$MS.MS) 
repC = grep("C_",datos$MS.MS)
datos$rep = "rep"
datos$rep[repA] = "A"
datos$rep[repB] = "B"
datos$rep[repC] = "C"


datos$GS = gsub("GN=","",datos$GS)


```

# Trioxidation in mouse Skin



```{r, box1, echo = F, warning= F, include = F}

### Total Triox Peptides 
c = table(datos[c("GS", "age")])
c1 = table(datos[c("Pep", "age")])
box = as.data.frame(c)
box1 = as.data.frame(c1)
ggboxplot(box, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "Age", ylab = "Number of peptides", main= "Total Peptides per Protein") + stat_compare_means(method = "anova")  + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5) 
ggboxplot(box1, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "Age", ylab = "Number of peptides", main = "Total Peptides per age group ") + stat_compare_means(method = "anova") + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5)

totales = addmargins(c)
write.csv(totales, file = "Total_peptides_skin.csv")
table(datos$age)
df = as.data.frame(table(datos$GS))
df_ord = df[order(df$Freq),]
tail(df_ord)
```



```{r, box2, echo = F, warning= F}
### Proteins with same modifications
uniq = unique(datos[c("GS" ,"age","Pep","rep")])
uniq1 = unique(datos[c("age","Pep","rep")])
b = table(uniq[,c("GS", "age")])
b1 = table(uniq1[,c("Pep","age")])
box1 = as.data.frame(b)
box2 = as.data.frame(b1)
ggboxplot(box1, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Peptides", main = "Number of peptides per protein") + stat_compare_means(method = "anova") + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5) + labs(caption = "Number of peptides grouped by protein and age")

ggboxplot(box2, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Peptides", main = "Number of different peptides per age group") + stat_compare_means(method = "anova") + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5) + labs(caption = "Number of different peptides grouped by age")

totales_unicos = addmargins(b)
pep_unicos = addmargins(b1)
write.csv(totales_unicos, file = "Unique_peptides_skin.csv")
write.csv(pep_unicos, file = "peptidos_unicos.csv")

table(uniq$age)


uniq1 = unique(uniq[c("GS", "age")])

uno = uniq1$GS[which(uniq1$age == "01")]
seis = uniq1$GS[which(uniq1$age == "06")]
d8 = uniq1$GS[which(uniq1$age == "18")]
v4 = uniq1$GS[which(uniq1$age == "24")]

#venn.diagram( x = list(uno,seis,d8, v4), category.names = c("01", "06", "18", "24"), filename = "ven_unico.png", output = T)
```

### Number of Trioxidations per protein

```{r, box7, echo = F, warning= F}

triox = str_count(datos$Pep1, "C3")
datos$triox =triox
posiciones = datos$pep_var_mod_pos %>% str_locate_all("3") %>% sapply(., function(x) x[,1]) 


lista = list()
for(x in 1:length(posiciones)){
  inicial = datos$pep_start[x]
  sum = unlist(posiciones[x]) + inicial-3
  lista = append(lista, list(sum))
  }


df = as.data.frame(do.call(rbind, lista))
datos = cbind(datos, df)
datos$pos = paste(datos$V1, datos$V2, datos$V3, sep = " ")

datos$pos = Map(unique, strsplit(datos$pos, " "))
datos$pos = as.character(datos$pos)
datos$pos = gsub("c", "", gsub('"', "",datos$pos))
datos$pos = gsub("[()]", "", datos$pos)



write.csv(datos, file = "procesed_data_skin.csv")

uniq = unique(datos[c("GS" ,"age","pos","triox", "rep")])
ag = aggregate(uniq$triox, by = list(uniq$age, uniq$GS, uniq$rep), FUN = sum)


uni = unique(datos[c("GS" ,"age","pos","triox")])
uni1 = unique(datos[c("Pep" ,"age","pos","triox")])

b = table(uniq[,c("GS", "age")])
b1 = table(uni1[,c("Pep", "age")])
box1 = as.data.frame(b)
box2 = as.data.frame(b1)
ggboxplot(box1, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Trioxidations", main = "Number of Trioxidations per protein") + stat_compare_means(method = "anova") + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5) + labs(caption = "Boxplot of the number of trioxidations grouped by protein and age")
totales_unicos = addmargins(b)

ggboxplot(box2, x = "age", y = "Freq", color = "age", palette = "jco", xlab = "age", ylab = "Number of Trioxidations", main= "Number of Trioxidations per Peptide") + stat_compare_means(method = "anova") + stat_summary(fun.data = mean_se, geom = "errorbar") + stat_boxplot(geom='errorbar', linetype=1, width=0.5) + labs(caption = "Boxplot of the number of trioxidations grouped by peptide and age")


g1A = ag[ag$Group.1 =="01" & ag$Group.3 == "A",]
g1B = ag[ag$Group.1 == "01" & ag$Group.3 == "B",]
g1C = ag[ag$Group.1 == "01" & ag$Group.3 == "C",]
g6A = ag[ag$Group.1 == "06" & ag$Group.3 == "A",]
g6B = ag[ag$Group.1 == "06" & ag$Group.3 == "B",]
g6C = ag[ag$Group.1 == "06" & ag$Group.3 == "C",]
g18A = ag[ag$Group.1 == "18" & ag$Group.3 == "A",]
g18B = ag[ag$Group.1 == "18" & ag$Group.3 == "B",]
g18C = ag[ag$Group.1 == "18" & ag$Group.3 == "C",]
g24A = ag[ag$Group.1 == "24" & ag$Group.3 == "A",]
g24B = ag[ag$Group.1 == "24" & ag$Group.3 == "B",]
g24C = ag[ag$Group.1 == "24" & ag$Group.3 == "C",]


lista = list(g1A,g1B,g1C,g6A,g6B,g6C,g18A,g18B,g18C,g24A,g24B,g24C)
junto = purrr::reduce(lista,full_join, by='Group.2')
df_final = junto[,c(4,7,10,13,16,19,22,25,28,31,34,37)]
colnames(df_final) = c("g01_A","g01_B","g01_C","g06_A","g06_B","g06_C","g18_A","g18_B","g18_C","g24_A","g24_B","g24_C")
rownames(df_final) = junto$Group.2

df_final[is.na(df_final)] = 0


groups = gsub("*_.", "", colnames( df_final ))
groups = factor(groups, levels = c("g01","g06","g18","g24"))
design = model.matrix( ~ 0 + groups )
colnames(design) = c("g01","g06","g18","g24")
dge = DGEList(counts=df_final);
dge = calcNormFactors(dge, method = "TMM")  
v = voom(dge, design)
fit = lmFit(v, design) 

cont.matrix = makeContrasts(g24vg01 = g24 - g01, g18vg01 = g18-g01, g06vg01 = g06 - g01, g24vg06 = g24 - g06, g18vg06 = g18 - g06, levels=design)
fit2 = contrasts.fit(fit, cont.matrix)
fit2 =  eBayes(fit2, trend=FALSE)
toptable = topTable(fit2, number = "all", confint=TRUE, adjust.method = "BH")

table(toptable$P.Value < 0.05)

metadatos = unique(datos[,c("GS","prot_desc")])
df_final$GS = rownames(df_final)
metadatos1 = merge(df_final, metadatos, by = "GS", all.x = T)


sig_p = toptable[which(toptable$P.Value < 0.05),]
sig_p$GS = rownames(sig_p)

tabla_sigp = merge(sig_p, metadatos, by= "GS")
tabla_sigp = tabla_sigp[order(tabla_sigp$g24vg01),]
up = tabla_sigp[which(tabla_sigp$g24vg01 > 0 & tabla_sigp$g18vg01 > 0),]



df_final = mutate(df_final, g01 = (g01_A + g01_B + g01_C)/3, g06 = (g06_A + g06_B + g06_C)/3, g18 = (g18_A + g18_B + g18_C)/3, g24 = (g24_A + g24_B+ g24_C)/3)

write.csv(df_final, file = "triox_count_skin.csv")
write.csv(tabla_sigp, file = "sig_triox_skin.csv")

datos_tabla_larga = gather(data = df_final[,c("g01","g06","g18","g24")], key = "group", value = "triox")

#ggplot(data = datos_tabla_larga, aes(x = group, y = triox, colour = group)) +
 #   geom_boxplot() +
  #  theme_bw() +
   # theme(legend.position = "none") + stat_compare_means(method = "anova")


```



### Differential expression analysis

```{r, box3, echo = F, warning= F}
uniq = unique(datos[c("GS" ,"age","Pep","prot_matches_sig", "rep")])
agrup2 = aggregate(uniq$prot_matches_sig, by = list(uniq$age, uniq$rep, uniq$GS), FUN = sum)


g1A = agrup2[agrup2$Group.1 =="01" & agrup2$Group.2 == "A",]
g1B = agrup2[agrup2$Group.1 == "01" & agrup2$Group.2 == "B",]
g1C = agrup2[agrup2$Group.1 == "01" & agrup2$Group.2 == "C",]
g6A = agrup2[agrup2$Group.1 == "06" & agrup2$Group.2 == "A",]
g6B = agrup2[agrup2$Group.1 == "06" & agrup2$Group.2 == "B",]
g6C = agrup2[agrup2$Group.1 == "06" & agrup2$Group.2 == "C",]
g18A = agrup2[agrup2$Group.1 == "18" & agrup2$Group.2 == "A",]
g18B = agrup2[agrup2$Group.1 == "18" & agrup2$Group.2 == "B",]
g18C = agrup2[agrup2$Group.1 == "18" & agrup2$Group.2 == "C",]
g24A = agrup2[agrup2$Group.1 == "24" & agrup2$Group.2 == "A",]
g24B = agrup2[agrup2$Group.1 == "24" & agrup2$Group.2 == "B",]
g24C = agrup2[agrup2$Group.1 == "24" & agrup2$Group.2 == "C",]


lista = list(g1A,g1B,g1C,g6A,g6B,g6C,g18A,g18B,g18C,g24A,g24B,g24C)
junto = purrr::reduce(lista,full_join, by='Group.3')
df_final = junto[,c(4,7,10,13,16,19,22,25,28,31,34,37)]
colnames(df_final) = c("g01_A","g01_B","g01_C","g06_A","g06_B","g06_C","g18_A","g18_B","g18_C","g24_A","g24_B","g24_C")
rownames(df_final) = junto$Group.3

df_final[is.na(df_final)] = 0



#write.csv(df_final, file = "prot_matches_sig_skin.csv")

totals = apply(X= df_final, MARGIN=2, FUN= sum)
mean = c(mean(totals[1:3]), mean(totals[4:6]), mean(totals[7:9]), mean(totals[10:12]))
sd = c(sd(totals[1:3]), sd(totals[4:6]), sd(totals[7:9]), sd(totals[10:12]))


tot = cbind(mean, sd)
rownames(tot) = c("g01","g06","g18","g24")
tot

groups = gsub("*_.", "", colnames( df_final ))
groups = factor(groups, levels = c("g01","g06","g18","g24"))
design = model.matrix( ~ 0 + groups )
colnames(design) = c("g01","g06","g18","g24")
dge = DGEList(counts=df_final);
dge = calcNormFactors(dge, method = "TMM")  
v = voom(dge, design)
fit = lmFit(v, design) 

cont.matrix = makeContrasts(g24vg01 = g24 - g01, g18vg01 = g18-g01, g06vg01 = g06 - g01, g24vg06 = g24 - g06, g18vg06 = g18 - g06, levels=design)
fit2 = contrasts.fit(fit, cont.matrix)
fit2 =  eBayes(fit2, trend=FALSE)
toptable = topTable(fit2, number = "all", confint=TRUE, adjust.method = "BH")

table(toptable$P.Value < 0.05)


metadatos = unique(datos[,c("GS","prot_desc")])
df_final$GS = rownames(df_final)
metadatos1 = merge(df_final, metadatos, by = "GS", all.x = T)


sig_p = toptable[which(toptable$P.Value < 0.05),]
sig_p$GS = rownames(sig_p)

tabla_sigp = merge(sig_p, metadatos, by= "GS")
tabla_sigp = tabla_sigp[order(tabla_sigp$g24vg01),]
up = tabla_sigp[which(tabla_sigp$g24vg01 > 0 & tabla_sigp$g18vg01 > 0),]

matriz_sig = df_final[up$GS,]

#write.csv(matriz_sig, file = "matriz_sig.csv")

mat = as.matrix(matriz_sig[,1:12])
heatmap(mat)


up %>%
  kbl(caption = "Differential expression analysis results") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% footnote(general = "Proteins more present in the older groups (g24 - g18) in relation to the younger groups (g06 - g01). All p-values are < 0.05",footnote_as_chunk = T)

#write.csv(tabla_sigp, file = "sig_results_skin.csv")

toptable$GS = rownames(toptable)

toptable$expression = ifelse(toptable$P.Value < 0.05 & abs(toptable$g24vg01) >=1 & abs(toptable$g18vg01) >= 1, 
                     ifelse(toptable$g24vg01 > 1 & toptable$g18vg01 > 1,'Up','Down'),
                     'Stable')


p <- ggplot(data = toptable, 
            aes(x = g24vg01, 
                y = -log10(toptable$P.Value), 
                colour=expression,
                label = toptable$GS)) +
  geom_point(alpha=0.4, size=3.5) +
  scale_color_manual(values=c("blue", "grey","red"))+
  xlim(c(-4.5, 4.5)) +
  geom_vline(xintercept=c(-1,1),lty=4,col="black",lwd=0.8) +
  geom_hline(yintercept = 1.301,lty=4,col="black",lwd=0.8) +
  labs(x="log2(fold change)",
       y="-log10 (adj.p-value)",
       title="Differential expression")  +
  theme_bw()+
  theme(plot.title = element_text(hjust = 0.5), 
        legend.position="right", 
        legend.title = element_blank())

p

p3 <- ggplot(toptable, aes(g24vg01, -log(P.Value,10))) +
  geom_point(aes(color = expression), size = 2/5) +
  xlab(expression("log"[2]*"FC")) + 
  ylab(expression("-log"[10]*"FDR")) +
  scale_color_viridis_d() +
  guides(colour = guide_legend(override.aes = list(size=1.5))) 

p3



fil = up[up$GS == "Myh1" | up$GS == "Krt5" | up$GS == "Krt17" | up$GS == "Actn2", c("GS","F", "P.Value")]
df_f = df_final[df_final$GS == "Myh1" | df_final$GS == "Krt5" | df_final$GS == "Krt17" | df_final$GS == "Actn2",]

mean = sapply(seq(2, ncol(df_f), 3), function(j) apply(df_f[, j+(-1:1)],1,mean))
sd = sapply(seq(2, ncol(df_f), 3), function(j) apply(df_f[, j+(-1:1)],1,sd))

mean = as.data.frame(mean)
sd = as.data.frame(sd)
mean$GS = rownames(mean)
sd$GS = rownames(sd)

descriptive = merge(mean, sd, by ="GS")
descriptive = merge(descriptive, fil, by ="GS")

#write.csv(descriptive, file = "descriptive_triox.csv")
```
### Over representation Analysis

```{r, box4, echo = F, warning= F}

ego  = enrichGO(gene          = up$GS,
                keyType =     "SYMBOL",
                OrgDb         = org.Mm.eg.db,
                ont           = "ALL",
                pAdjustMethod = "BH",
                pvalueCutoff  = 0.05,
                readable      = TRUE)

ego_BP = ego[ego$ONTOLOGY == "BP" & ego$Count > 3,]



ego_BP %>%
  kbl(caption = "Biological Process") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% footnote(general = "Biological Processes of proteins more present in the older groups in relation to the younger groups. All p-values are < 0.05",footnote_as_chunk = T)

write.csv(ego, file = "ora_skin.csv")

org = org.Mm.eg.db

ids = bitr(up$GS, fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org)
dedup_ids = ids[!duplicated(ids[c("SYMBOL")]),]
df2 = up[up$GS %in% dedup_ids$SYMBOL,]
df2 = merge(x = df2, y = dedup_ids, by.x = "GS", by.y = "SYMBOL")

kegg = enrichKEGG(gene = df2$ENTREZID, organism = 'mmu', pvalueCutoff = 0.05)

kegg %>%
  kbl(caption = "Kegg Pathways") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% footnote(general = "KEGG pathways of proteins more present in the older groups in relation to the younger groups. All p-values are < 0.05",footnote_as_chunk = T)

write.csv(kegg, file = "rutas_ora_skin.csv")

```

### Gene Set Enrichment Analysis

```{r, box5, echo = F, warning= F}
genelist = toptable[,"g24vg01"]
names(genelist) = rownames(toptable)
genelist = sort(genelist, decreasing = T)

gse = gseGO(geneList = genelist, 
             ont ="ALL", 
             keyType = "SYMBOL", 
             nPerm = 10000, 
             minGSSize = 2, 
             maxGSSize = 800, 
             pvalueCutoff = 0.05, 
             verbose = TRUE, 
             OrgDb = org,
             pAdjustMethod = "none")

write.csv(gse, file = "gse_Skin.csv")


gse_pos = gse[gse$ONTOLOGY == "BP" & gse$enrichmentScore > 0 & gse$setSize > 9,]

gse_pos %>%
  kbl(caption = "Gene Set Enrichment Analysis") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% footnote(general = "Gene Ontology terms enriched (NES value > 0) or depleted (NES value < 0) in older mices in relation to young mices",footnote_as_chunk = T)

dotplot(gse, showCategory=5, split=".sign", decreasing = T, x = "count") + facet_grid(.~.sign) + labs(caption = "Gene Ontology terms enriched (NES value > 0) or depleted (NES value < 0) in older mices in relation to young mices")

ids = bitr(names(genelist), fromType = "SYMBOL", toType = "ENTREZID", OrgDb=org)
dedup_ids = ids[!duplicated(ids[c("SYMBOL")]),]
df2 = toptable[rownames(toptable) %in% dedup_ids$SYMBOL,]
df2$X = rownames(df2)
df2 = merge(x = df2, y = dedup_ids, by.x = "X", by.y = "SYMBOL")
kegg_gene_list =  df2$g24vg01 
names(kegg_gene_list) = df2$ENTREZID
kegg_gene_list = sort(kegg_gene_list, decreasing = TRUE)

kk2 = gseKEGG(geneList     =  kegg_gene_list,
               organism     = "mmu",
               nPerm        = 10000,
               minGSSize    = 2,
               maxGSSize    = 800,
               pvalueCutoff = 0.05,
               pAdjustMethod = "none",
               keyType       = "ncbi-geneid")

kk2 %>%
  kbl(caption = "Kegg Pathways") %>%
  kable_classic(full_width = F, html_font = "Cambria") %>% footnote(general = "KEGG pathways of proteins more present in the older groups in relation to the younger groups. All p-values are < 0.05",footnote_as_chunk = T)

write.csv(kk2, file = "rutas_gse_skin.csv")

dotplot(kk2, showCategory = 5, title = "Enriched Pathways" , split=".sign", x = "count", decreasing = T) + facet_grid(.~.sign) + labs(caption = "Different KEEG enriched pathways (NES value > 0) or depleted (NES value < 0) in older mices in relation to young mices")

emapplot(kk2)

```




